#!/bin/sh -x
set -eu
host="$1"
shift 1

# "root@host" -> "host_root"
dirname="$(echo "$host" | sed -r 's/(.*)@(.*)/\2_\1/')"
cd "$HOME"/mnt/ssh  # TODO: `~/.mnt`
mkdir -p "$dirname"
sshfs \
    "$host":/ "$dirname" \
    "$@" \
    -o idmap=user,workaround=rename,reconnect,transform_symlinks,allow_root
