#!/bin/sh
####
## Create relative symbolic links from the files in the repository in
## the current directory to home directory.
##
## NOTE: repository outside of home directory is possible but not
## supported (because not needed).
####


ovw=""
[ x"$1" = x"-f" ] && {
  echo "Force-pre-remove."
  ovw="."
}


unpath(){
  ## cd "$1/$(unpath "$1")" -> same directory
  fn="$1"
  #fn="$(dirname "$1")"
  echo "$fn" \
    | sed -r 's,/?$,/,' \
    | sed -r 's,^\./,,' \
    | sed -r 's,[^/]+/,../,g'
}

## The repository is supposed to be in the current dir
repodir="$(pwd)/"
home="$HOME/"
reporel="$(echo "$repodir" | sed -rn "s!^$home/*!! p" )" 
[ -z "$reporel" ] && {
  echo "repodir '$repodir' is not under home '$home'. Aborting."
  exit 1
}


tf="$(mktemp)" && {
  git ls-tree -r --name-only HEAD > "$tf" && \
  cd "$home" && (
    cat "$tf" | while read fn; do
      # fn is repo-relative, curdir is home
      fd="$(dirname "$fn")"
      mkdir -pv "$fd"
      [ $ovw ] && {
        [ -e "$fn" ] && {
          mv "$fn" "${fn}._0dotlink.bk"
          rm -v "$fn"
        }
        # 2>&1 | grep -v "No such file or directory$"
      }
      target="$(unpath "$fd")${reporel}${fn}"
      ## NOTE: all (directory) paths are supposed to end in slash
      [ -L "$fn" ] && {
        current_target="$(readlink "$fn")"
        [ x"$current_target" = x"$target" ] && {
          ## Already linked where it should be
          continue
        }
      }
      ln -v -s "$target" "$fn"
    done
  )
  rm -v "$tf"
}
