#!/bin/sh -x

set -eu

repodir="$(dirname "$(readlink -e "$0")")"
repodir="$repodir/homedir/"

tempfile="$(mktemp)"
trap 'rm "$tempfile"' EXIT
# Note: `-X` did not go well with a broken symlink.
git ls-tree -r --name-only HEAD > "$tempfile"
rsync -v -HAax --files-from="$tempfile" "$@" ./ ~/
